#pragma once

#define EYES2D_USING_WINDOWS_7

#ifdef EYES2D_USING_DIRECTX_SDK
#define EYES2D_USING_XINPUT_1_3
#else
#ifdef EYES2D_USING_WINDOWS_7
#define EYES2D_USING_XINPUT_9_1
#else
#define EYES2D_USING_XINPUT_1_4
#endif // EYES2D_USING_WINDOWS_7
#endif // EYES2D_USING_DIRECTX_SDK
